[project]
name = "financial-time-series-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "yfinance>=0.2.66",
]
